{
	"version": 1574404089,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bg-sheet0.png",
		"images/butt_mulai-sheet0.png",
		"images/buttonload-sheet0.png",
		"images/butt_credits-sheet0.png",
		"images/bg_titleany-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite2-sheet0.png",
		"images/popup_sementara.png",
		"images/butt_sett-sheet0.png",
		"images/butt_sett-sheet1.png",
		"images/butt_close-sheet0.png",
		"images/butt_close-sheet1.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/bg_school-sheet0.png",
		"images/character_box-sheet0.png",
		"images/item-sheet0.png",
		"images/item-sheet1.png",
		"images/item_box-sheet0.png",
		"images/guide_book-sheet0.png",
		"images/guide_book-sheet1.png",
		"images/menu_more-sheet0.png",
		"images/menu_more-sheet1.png",
		"images/more_save-sheet0.png",
		"images/more_load-sheet0.png",
		"images/more_setting-sheet0.png",
		"images/more_exit-sheet0.png",
		"images/time_bar-sheet0.png",
		"images/dialogue_box-sheet0.png",
		"images/parameter_bar-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/energy_bar-sheet0.png",
		"images/mood_bar-sheet0.png",
		"images/education_value.png",
		"images/name_text.png",
		"images/full_view_btn-sheet0.png",
		"images/peta-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/rumah-sheet0.png",
		"images/sekolah-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/tiledbackground2.png",
		"images/popup_guide-sheet0.png",
		"images/popup_guide-sheet1.png",
		"images/popup_calendar-sheet0.png",
		"images/popup_calendar-sheet1.png",
		"images/tiledbackground3.png",
		"images/tiledbackground4.png",
		"images/activity1-sheet0.png",
		"images/textactivity1.png",
		"media/bruh sound effect #2.ogg",
		"media/click2-sebastian-759472264.ogg",
		"media/click button 2-soundbible.com-911295385.m4a",
		"media/click button 2-soundbible.com-911295385.ogg",
		"media/voice_sans.ogg",
		"media/051. tsubomi (event bgm).ogg",
		"media/click2-sebastian-759472264.m4a",
		"media/100 - megalovania.m4a",
		"media/100 - megalovania.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"i, giorno giovanna, have a dream..mp4",
		"pathfind.js"
	]
}